language: ruby

sudo: false

rvm:
  - "2.3.1"

env:
  - DB=postgresql HOST=localhost:1025 DOMAIN=test.example.com

addons:
  postgresql: 9.4

before_script:
  - bundle exec rake db:create RAILS_ENV=test

script:
  - bundle exec rails db:migrate
  # Travis Raises
  # ActionView::Template::Error: Illegal nesting: Only properties may be nested beneath
  # properties. If I try and use scss-lint - even with require: false
  # https://github.com/brigade/scss-lint/issues/496
  # Replacing task 'rails full' with 'rails incomplete'
  - bundle exec rails incomplete 

notifications:
  email: true
  slack: bcs-io:j4u422myY0CcryFquMCAOi45
  webhooks:
    on_success: change
    on_failure: always
