# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17e9534b3e73bb72dbd9b4f151bb96e7c38fe26a2c313b03fa732ea449ce7a45186e647b23f00b5af1ba9d619e1c88ac1368fad7a63cdb232d39445a9aa28645

test:
  secret_key_base: c653018a366d366812c8e18224aba217f89d0963b5b5f83335d6540795ec9fcfe30b91543e2ddddd6b2c4efe6e02849e223a4256a3df714e0747a0e5afd350ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: # run: rails secret and add content here
